#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <memory>

class ConfigClass;

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void MainFormClose( wxCloseEvent& event );
		void WxPanel_Repaint( wxUpdateUIEvent& event );
		void m_button1_click( wxCommandEvent& event );
		void m_button2_click( wxCommandEvent& event );
		void m_radioBtn1_selected(wxCommandEvent& event);
		void m_radioBtn2_selected(wxCommandEvent& event);
		void m_radioBtn3_selected(wxCommandEvent& event);
		void m_scroll_rozmycie_upadate(wxScrollEvent& event);
		void m_button3_click(wxCommandEvent& event);
		void m_menuItem8_selected(wxCommandEvent& event);
		void m_toggleBtn_rysuj_toogled(wxCommandEvent& event);
		void m_toggle_button_gumka_toggled(wxCommandEvent& event);
		void m_slider_rozmiarRys_update(wxScrollEvent& event);
		void m_slider_poziomNalozenia_update(wxScrollEvent& event);
		void m_color1_changed(wxColourPickerEvent& event);

		void OnMouseMove(wxMouseEvent& evt);
		void OnMouseDown(wxMouseEvent& evt);
		void OnMouseUp(wxMouseEvent& evt);

	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
  void Repaint();
  void UpdateControls();
  ~GUIMyFrame1();
  std::shared_ptr<ConfigClass> cfg;
};

#endif // __GUIMyFrame1__
